version: '2'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: tcr_
    ports:
      - 80:80
      - 443:443
    networks:
      - back
  db:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db_data:/var/lib/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - back
  phpmhyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - back
networks:
  back:
volumes:
  db_data: